from typing import Literal
from enum import IntEnum

DEFAULT_CHROME_OPTIONS = [
    '--disable-search-engine-choice-screen',
    '--start-maximized'
]
DEFAULT_CHROME_EXTENSIONS = [
    '../chrome_extensions/ad_block_plus.crx'
]
ADBLOCK_EXTENSION_URL = ('https://www.crx4chrome.com/go.php?p=31928&i=cfhdojbkjhnklbpkdaibdccddilif'
                         'ddb&s=O3CUdPpTCIbEs&l=https%3A%2F%2Ff6.crx4chrome.com%2Fcrx.php%3Fi%3Dcfh'
                         'dojbkjhnklbpkdaibdccddilifddb%26v%3D4.6')

HEROES = Literal[
    # Strength
    "alchemist", "axe", "bristleback", "centaur_warrunner", "chaos_knight", "clockwerk", "dawnbreaker",
    "doom", "dragon_knight", "earth_spirit", "earthshaker", "elder_titan", "huskar", "kunkka",
    "legion_commander", "lifestealer", "lycan", "mars", "night_stalker", "ogre_magi", "omniknight",
    "phoenix", "primal_beast", "pudge", "slardar", "spirit_breaker", "sven", "tidehunter", "timbersaw",
    "tiny", "treant_protector", "tusk", "underlord", "undying", "wraith_king",

    # Agility
    "anti_mage", "bloodseeker", "bounty_hunter", "broodmother", "clinkz", "drow_ranger", "ember_spirit",
    "faceless_void", "gyrocopter", "hoodwink", "juggernaut", "kez", "lone_druid", "luna", "medusa", "meepo",
    "mirana", "monkey_king", "morphling", "naga_siren", "phantom_assassin", "phantom_lancer", "razor",
    "riki", "shadow_fiend", "slark", "sniper", "templar_assassin", "terrorblade", "troll_warlord",
    "ursa", "vengeful_spirit", "viper", "weaver",

    # Intelligence
    "ancient_apparition", "chen", "crystal_maiden", "dark_seer", "dark_willow", "disruptor", "enchantress",
    "grimstroke", "invoker", "jakiro", "keeper_of_the_light", "leshrac", "lich", "lina", "lion", "muerta",
    "necrophos", "oracle", "outworld_destroyer", "puck", "pugna", "queen_of_pain", "ringmaster", "rubick",
    "shadow_demon", "shadow_shaman", "silencer", "skywrath_mage", "storm_spirit", "tinker", "warlock",
    "winter_wyvern", "witch_doctor", "zeus",

    # Universal
    "abaddon", "arc_warden", "bane", "batrider", "beastmaster", "brewmaster", "dazzle", "death_prophet",
    "enigma", "io", "magnus", "marci", "natures_prophet", "nyx_assassin", "pangolier", "sand_king",
    "snapfire", "spectre", "techies", "venomancer", "visage", "void_spirit", "windranger"
]

ID2HERO = {
    1: "Anti-Mage",
    2: "Axe",
    3: "Bane",
    4: "Bloodseeker",
    5: "Crystal Maiden",
    6: "Drow Ranger",
    7: "Earthshaker",
    8: "Juggernaut",
    9: "Mirana",
    10: "Morphling",
    11: "Shadow Fiend",
    12: "Phantom Lancer",
    13: "Puck",
    14: "Pudge",
    15: "Razor",
    16: "Sand King",
    17: "Storm Spirit",
    18: "Sven",
    19: "Tiny",
    20: "Vengeful Spirit",
    21: "Windranger",
    22: "Zeus",
    23: "Kunkka",
    25: "Lina",
    26: "Lion",
    27: "Shadow Shaman",
    28: "Slardar",
    29: "Tidehunter",
    30: "Witch Doctor",
    31: "Lich",
    32: "Riki",
    33: "Enigma",
    34: "Tinker",
    35: "Sniper",
    36: "Necrophos",
    37: "Warlock",
    38: "Beastmaster",
    39: "Queen of Pain",
    40: "Venomancer",
    41: "Faceless Void",
    42: "Wraith King",
    43: "Death Prophet",
    44: "Phantom Assassin",
    45: "Pugna",
    46: "Templar Assassin",
    47: "Viper",
    48: "Luna",
    49: "Dragon Knight",
    50: "Dazzle",
    51: "Clockwerk",
    52: "Leshrac",
    53: "Nature's Prophet",
    54: "Lifestealer",
    55: "Dark Seer",
    56: "Clinkz",
    57: "Omniknight",
    58: "Enchantress",
    59: "Huskar",
    60: "Night Stalker",
    61: "Broodmother",
    62: "Bounty Hunter",
    63: "Weaver",
    64: "Jakiro",
    65: "Batrider",
    66: "Chen",
    67: "Spectre",
    68: "Ancient Apparition",
    69: "Doom",
    70: "Ursa",
    71: "Spirit Breaker",
    72: "Gyrocopter",
    73: "Alchemist",
    74: "Invoker",
    75: "Silencer",
    76: "Outworld Destroyer",
    77: "Lycan",
    78: "Brewmaster",
    79: "Shadow Demon",
    80: "Lone Druid",
    81: "Chaos Knight",
    82: "Meepo",
    83: "Treant Protector",
    84: "Ogre Magi",
    85: "Undying",
    86: "Rubick",
    87: "Disruptor",
    88: "Nyx Assassin",
    89: "Naga Siren",
    90: "Keeper of the Light",
    91: "Io",
    92: "Visage",
    93: "Slark",
    94: "Medusa",
    95: "Troll Warlord",
    96: "Centaur Warrunner",
    97: "Magnus",
    98: "Timbersaw",
    99: "Bristleback",
    100: "Tusk",
    101: "Skywrath Mage",
    102: "Abaddon",
    103: "Elder Titan",
    104: "Legion Commander",
    105: "Techies",
    106: "Ember Spirit",
    107: "Earth Spirit",
    108: "Underlord",
    109: "Terrorblade",
    110: "Phoenix",
    111: "Oracle",
    112: "Winter Wyvern",
    113: "Arc Warden",
    114: "Monkey King",
    119: "Dark Willow",
    120: "Pangolier",
    121: "Grimstroke",
    123: "Hoodwink",
    126: "Void Spirit",
    128: "Snapfire",
    129: "Mars",
    131: "Ringmaster",
    135: "Dawnbreaker",
    136: "Marci",
    137: "Primal Beast",
    138: "Muerta",
    145: "Kez"
}

HERO2ID = {
    "Anti-Mage": 1,
    "Axe": 2,
    "Bane": 3,
    "Bloodseeker": 4,
    "Crystal Maiden": 5,
    "Drow Ranger": 6,
    "Earthshaker": 7,
    "Juggernaut": 8,
    "Mirana": 9,
    "Morphling": 10,
    "Shadow Fiend": 11,
    "Phantom Lancer": 12,
    "Puck": 13,
    "Pudge": 14,
    "Razor": 15,
    "Sand King": 16,
    "Storm Spirit": 17,
    "Sven": 18,
    "Tiny": 19,
    "Vengeful Spirit": 20,
    "Windranger": 21,
    "Zeus": 22,
    "Kunkka": 23,
    "Lina": 25,
    "Lion": 26,
    "Shadow Shaman": 27,
    "Slardar": 28,
    "Tidehunter": 29,
    "Witch Doctor": 30,
    "Lich": 31,
    "Riki": 32,
    "Enigma": 33,
    "Tinker": 34,
    "Sniper": 35,
    "Necrophos": 36,
    "Warlock": 37,
    "Beastmaster": 38,
    "Queen of Pain": 39,
    "Venomancer": 40,
    "Faceless Void": 41,
    "Wraith King": 42,
    "Death Prophet": 43,
    "Phantom Assassin": 44,
    "Pugna": 45,
    "Templar Assassin": 46,
    "Viper": 47,
    "Luna": 48,
    "Dragon Knight": 49,
    "Dazzle": 50,
    "Clockwerk": 51,
    "Leshrac": 52,
    "Nature's Prophet": 53,
    "Lifestealer": 54,
    "Dark Seer": 55,
    "Clinkz": 56,
    "Omniknight": 57,
    "Enchantress": 58,
    "Huskar": 59,
    "Night Stalker": 60,
    "Broodmother": 61,
    "Bounty Hunter": 62,
    "Weaver": 63,
    "Jakiro": 64,
    "Batrider": 65,
    "Chen": 66,
    "Spectre": 67,
    "Ancient Apparition": 68,
    "Doom": 69,
    "Ursa": 70,
    "Spirit Breaker": 71,
    "Gyrocopter": 72,
    "Alchemist": 73,
    "Invoker": 74,
    "Silencer": 75,
    "Outworld Destroyer": 76,
    "Lycan": 77,
    "Brewmaster": 78,
    "Shadow Demon": 79,
    "Lone Druid": 80,
    "Chaos Knight": 81,
    "Meepo": 82,
    "Treant Protector": 83,
    "Ogre Magi": 84,
    "Undying": 85,
    "Rubick": 86,
    "Disruptor": 87,
    "Nyx Assassin": 88,
    "Naga Siren": 89,
    "Keeper of the Light": 90,
    "Io": 91,
    "Visage": 92,
    "Slark": 93,
    "Medusa": 94,
    "Troll Warlord": 95,
    "Centaur Warrunner": 96,
    "Magnus": 97,
    "Timbersaw": 98,
    "Bristleback": 99,
    "Tusk": 100,
    "Skywrath Mage": 101,
    "Abaddon": 102,
    "Elder Titan": 103,
    "Legion Commander": 104,
    "Techies": 105,
    "Ember Spirit": 106,
    "Earth Spirit": 107,
    "Underlord": 108,
    "Terrorblade": 109,
    "Phoenix": 110,
    "Oracle": 111,
    "Winter Wyvern": 112,
    "Arc Warden": 113,
    "Monkey King": 114,
    "Dark Willow": 119,
    "Pangolier": 120,
    "Grimstroke": 121,
    "Hoodwink": 123,
    "Void Spirit": 126,
    "Snapfire": 128,
    "Mars": 129,
    "Ringmaster": 131,
    "Dawnbreaker": 135,
    "Marci": 136,
    "Primal Beast": 137,
    "Muerta": 138,
    "Kez": 145
}

MECHANICS = Literal[
    'abilities', 'accuracy', 'agility', 'ancient', 'armor manipulation', 'armor', 'armory', 'attack damage',
    'attack range', 'attack speed', 'attack animation', 'attack backswing', 'attack immunity', 'attack point',
    'attributes', 'aura', 'ban', 'banish', 'barracks', 'barrier', 'bash', 'basic dispel', 'blind', 'blink', 'break',
    'buildings', 'buyback', 'cast animation', 'cast backswing', 'cast point', 'channeling', 'chat wheel', 'cheats',
    'collision size', 'commend', 'console commands', 'controls', 'cooldown', 'courier', 'creep control techniques',
    'creeps', 'critical strike', 'custom games', 'cyclone', 'damage barrier', 'damage block', 'damage types',
    'damage amplification', 'damage manipulation', 'damage negation', 'damage over time', 'damage reduction',
    'debuff immunity', 'denying', 'disarm', 'disassembling', 'disjoint', 'drop list', 'effective hp', 'ethereal',
    'evasion', 'events', 'experience', 'expose', 'farming', 'fear', 'flying vision', 'forced movement', 'game map',
    'game modes', 'ganking', 'gems', 'gifting', 'gold', 'ground vision', 'hp removal', 'hud', 'health regeneration',
    'health', 'hex', 'hidden', 'hide', 'hotkeys', 'hypnosis', 'illusions', 'initiating', 'instant attack',
    'intelligence', 'invisibility', 'invulnerability', 'item drop system', 'item sharing', 'items', 'jungle',
    'jungling', 'lane creeps', 'lanes', 'launch options', 'leash', 'lifesteal', 'magic resistance', 'magical damage',
    'mana regeneration', 'mana break', 'mana', 'matchmaking rating', 'minimap', 'modding', 'movement speed', 'music',
    'mute', 'neutral creeps', 'outposts', 'patches', 'phased', 'physical damage', 'player behavior summary', 'priority',
    'projectile speed', 'pseudo-random distribution', 'pure damage', 'pushing', 'quality', 'rarity', 'recipes',
    'replay', 'report', 'restoration manipulation', 'roles', 'root', 'runes', 'scan', 'shackle', 'shared vision',
    'shops', 'silence', 'slow resistance', 'slow', 'spectating', 'spell damage', 'spell amplification', 'spell damage',
    'spell immunity', 'spell lifesteal', 'status resistance', 'steam market', 'strength', 'strong dispel', 'stun',
    'summons', 'talents', 'taunt', 'teleport', 'time of day', 'total attack damage', 'towers', 'trading', 'trap',
    'trees', 'true strike', 'true random distribution', 'true sight', 'turn rate', 'versions', 'vision', 'wards'
]

ITEM_TYPE = Literal['shop_items', 'neutral_items', 'enchantment']

SHOP_ITEMS = Literal[
    'Alert Enchantment', 'Keen-Eyed Enchantment', 'Audacious Enchantment', 'Mystical Enchantment',
    'Boundless Enchantment', 'Quickened Enchantment', 'Brawny Enchantment', 'Timeless Enchantment',
    'Crude Enchantment', 'Titanic Enchantment', 'Evolved Enchantment', 'Tough Enchantment',
    'Feverish Enchantment', 'Vampiric Enchantment', 'Fleetfooted Enchantment', 'Vast Enchantment',
    'Greedy Enchantment', 'Wise Enchantment'
]
NEUTRAL_ITEMS = Literal[
    "book of the dead", "brigand's blade", "chipped vest", "crippling crossbow", "dezun bloodrite", "divine regalia",
    "dormant curio", "essence ring", "fallen sky", "gale guard", "giant's maul", "gunpowder gauntlet",
    "helm of the undying", "jidi pollen bag", "kobold cup", "magnifying monocle", "mana draught", "minotaur horn",
    "occult bracelet", "outworld staff", "pollywog charm", "poor man's shield", "psychic headband", "pyrrhic cloak",
    "ripper's lash", "searing signet", "serrated shiv", "sister's shroud", "spark of courage", "spider legs",
    "stygian desolator", "tumbler's toy", "unrelenting eye", "whisper of the dread",
]
ENCHANTMENT_ITEMS = Literal[
    "abyssal blade", "aeon disk", "aether lens", "aghanim's scepter", "aghanim's shard", "arcane blink", "arcane boots",
    "armlet of mordiggian", "assault cuirass", "band of elvenskin", "battle fury", "belt of strength", "black king bar",
    "blade mail", "blade of alacrity", "blades of attack", "blink dagger", "blitz knuckles", "blood grenade",
    "bloodstone", "bloodthorn", "boots of bearing", "boots of speed", "boots of travel", "bottle", "bracer",
    "broadsword", "buckler", "butterfly", "chainmail", "circlet", "clarity", "claymore", "cloak", "cornucopia",
    "crimson guard", "crown", "crystalys", "daedalus", "dagon", "demon edge", "desolator", "diadem", "diffusal blade",
    "disperser", "divine rapier", "dragon lance", "drum of endurance", "dust of appearance", "eaglesong", "echo sabre",
    "enchanted mango", "energy booster", "eternal shroud", "ethereal blade", "eul's scepter of divinity",
    "eye of skadi", "faerie fire", "falcon blade", "fluffy hat", "force staff", "gauntlets of strength",
    "gem of true sight", "ghost scepter", "gleipnir", "glimmer cape", "gloves of haste", "guardian greaves",
    "hand of midas", "harpoon", "headdress", "healing salve", "heart of tarrasque", "heaven's halberd",
    "helm of iron will", "helm of the dominator", "helm of the overlord", "holy locket", "hurricane pike", "hyperstone",
    "infused raindrops", "iron branch", "javelin", "kaya and sange", "kaya", "khanda", "linken's sphere", "lotus orb",
    "maelstrom", "mage slayer", "magic stick", "magic wand", "manta style", "mantle of intelligence", "mask of madness",
    "mekansm", "meteor hammer", "mithril hammer", "mjollnir", "monkey king bar", "moon shard", "morbid mask",
    "mystic staff", "nullifier", "null talisman", "oblivion staff", "observer ward", "octarine core", "ogre axe",
    "orb of blight", "orb of corrosion", "orb of frost", "orb of venom", "orchid malevolence", "overwhelming blink",
    "parasma", "pavise", "perseverance", "phase boots", "phylactery", "pipe of insight", "platemail", "point booster",
    "power treads", "quelling blade", "radiance", "reaver", "refresher orb", "revenant's brooch", "ring of basilius",
    "ring of health", "ring of protection", "ring of regen", "ring of tarrasque", "robe of the magi", "rod of atos",
    "sacred relic", "sage's mask", "sange and yasha", "sange", "satanic", "scythe of vyse", "sentry ward",
    "shadow amulet", "shadow blade", "shiva's guard", "silver edge", "skull basher", "slippers of agility",
    "smoke of deceit", "solar crest", "soul booster", "soul ring", "spirit vessel", "staff of wizardry", "swift blink",
    "talisman of evasion", "tango", "tiara of selemene", "town portal scroll", "tranquil boots", "ultimate orb",
    "urn of shadows", "vanguard", "veil of discord", "vitality booster", "vladmir's offering", "void stone",
    "voodoo mask", "wind lace", "wind waker", "witch blade", "wraith band", "yasha and kaya", "yasha",
]
